### ISSUE TITLE
How to import Schema.sql with Hasura docker-compose

### ISSUE THREAD

**Issue by mnlbox** [hasura/3factor-example#12]
Hi @tirumaraiselvan,

I install Hasura with docker-compose and want to do step bu step to implement this example app.
Can you guide me how to import [Schema.sql](https://github.com/hasura/3factor-example/blob/master/schema.sql) with Hasura docker-compose?
In this example guide you work with a local Postgres.

**/CC:** @wawhal, @surendran82

**Comment by tirumaraiselvan** [comment]
Hey @mnlbox 

Do you have access to your Postgres db?

**Comment by mnlbox** [comment]
@tirumaraiselvan I run my Hasura instance with this guide:
https://docs.hasura.io/1.0/graphql/manual/getting-started/docker-simple.html

How we can access to this Postgres? :thinking:

**Comment by tirumaraiselvan** [comment]
@mnlbox Ah! Seems like the Postgres container is not exposed to localhost in docker-compose manifest. We will fix it.

In the meanwhile, you can go to Hasura console -> Data tab

**Comment by tirumaraiselvan** [comment]
@mnlbox Ah! Seems like the Postgres container is not exposed to localhost in docker-compose manifest. We will fix it.

In the meanwhile, you can go to Hasura console -> Data tab -> Run SQL and copy paste the contents of schema.sql there. And execute.

**Comment by mnlbox** [comment]
@tirumaraiselvan Thanks man.
Maybe related: https://github.com/hasura/graphql-engine/issues/1424

**Comment by tirumaraiselvan** [comment]
Sorry, I accidently closed the issue. Do check out my comment with the
workaround.

**Comment by mnlbox** [comment]
Thanks @tirumaraiselvan I think expose Postgres and pgAdmin to local can be useful for this purpose :wink: 
Your temp solution (run SQL in Hasura console working well).

**Comment by tirumaraiselvan** [comment]
Resolved

**Comment by mnlbox** [comment]
@tirumaraiselvan Can you guide a little?

**Comment by tirumaraiselvan** [comment]
@mnlbox You can use pgadmin like here: https://github.com/hasura/graphql-engine/blob/master/install-manifests/docker-compose-pgadmin/docker-compose.yaml

Or you can use `network: host` in your docker-compose.yaml and connect to psql directly on port 5432

**Comment by jordanmkoncz** [comment]
For anyone else who has the same question as @mnlbox, I found a fairly easy way to achieve this.

1. Clone the repo
2. Add `docker-compose.yaml` to the repository root (see code below)
3. Run `docker-compose up -d`
4. Run `docker exec -i 3factor_postgres psql -U postgres postgres < schema.sql`

`docker-compose.yaml`:
```
version: '3.6'
services:
  postgres:
    image: "postgres:11.1"
    container_name: "3factor_postgres"
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
  graphql-engine:
    image: hasura/graphql-engine:v1.0.0-beta.4
    container_name: "3factor_hasura"
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
volumes:
  db_data:
```
